/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaNegocio;

/**
 *
 * @author miguelfc
 */
public class MenuVuelosDiarios extends javax.swing.JFrame {

    public static String codigoVuelo;
    /**
     * Creates new form MenuVuelosDiarios
     */
    public MenuVuelosDiarios() {
        initComponents();
        CBModificar = LogicaNegocio.rellenarListaVuelosDiarios(CBModificar);
        CBEliminar = LogicaNegocio.rellenarListaVuelosDiarios(CBEliminar);
        CBDatos = LogicaNegocio.rellenarListaVuelosDiarios(CBDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        lblBorrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrefijoDatos = new javax.swing.JLabel();
        lblPrefijoBaja4 = new javax.swing.JLabel();
        CBEliminar = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        lblTelfPasa2 = new javax.swing.JLabel();
        txtModificarCod = new javax.swing.JTextField();
        lblTelfAero2 = new javax.swing.JLabel();
        bntModificar = new javax.swing.JButton();
        lblModiCodigo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        CBModificar = new javax.swing.JComboBox<>();
        txtModiHoraLlegada = new javax.swing.JTextField();
        lblDireccion2 = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        txtNumPlazasOcu = new javax.swing.JTextField();
        lblDatos = new javax.swing.JLabel();
        lblMunicipio2 = new javax.swing.JLabel();
        lblPrefijoBaja2 = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        CBDatos = new javax.swing.JComboBox<>();
        lblNombre2 = new javax.swing.JLabel();
        txtModiHoraSalida = new javax.swing.JTextField();
        txtModificarFecha = new javax.swing.JTextField();
        lblTelfPasa4 = new javax.swing.JLabel();
        txtDatosCod = new javax.swing.JTextField();
        lblTelfAero4 = new javax.swing.JLabel();
        lblModiCodigo4 = new javax.swing.JLabel();
        txtDatosPlazas = new javax.swing.JTextField();
        lblMunicipio4 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        txtDatosSalida = new javax.swing.JTextField();
        txtDatosFecha = new javax.swing.JTextField();
        txtDatosPrecio = new javax.swing.JTextField();
        txtDatosLlegada = new javax.swing.JTextField();
        lblDireccion4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTempOrigen = new javax.swing.JTextField();
        txtTempDestino = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        jPanelSalida = new javax.swing.JMenu();
        jPanelLlegadas = new javax.swing.JMenu();
        jPanelRecaudaciones = new javax.swing.JMenu();
        jPanelVuelosCompañia = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBorrar.setText("DAR DE BAJA");

        lblPrefijoDatos.setText("Elegir el codigo del vuelo diario para ver sus datos:");

        lblPrefijoBaja4.setText("Elegir el codigo del vuelo diario a eliminar:");

        CBEliminar.setToolTipText("");
        CBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEliminarActionPerformed(evt);
            }
        });

        lblTelfPasa2.setText("Número de plazas ocupadas:");

        lblTelfAero2.setText("Precio del vuelo:");

        bntModificar.setText("Modificar");
        bntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificarActionPerformed(evt);
            }
        });

        lblModiCodigo2.setText("Codigo:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        CBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBModificarActionPerformed(evt);
            }
        });

        lblDireccion2.setText("Hora de salida real: ");

        lblModificar.setText("MODIFICAR");

        lblDatos.setText("VER DATOS");

        lblMunicipio2.setText("Hora de llegada real:");

        lblPrefijoBaja2.setText("Elegir el codigo del vuelo diario a modificar:");

        btnDatos.setText("Ver Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        CBDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDatosActionPerformed(evt);
            }
        });

        lblNombre2.setText("Fecha del vuelo:");

        lblTelfPasa4.setText("Número de plazas ocupadas:");

        lblTelfAero4.setText("Precio del vuelo:");

        lblModiCodigo4.setText("Codigo:");

        lblMunicipio4.setText("Hora de llegada real:");

        lblNombre4.setText("Fecha del vuelo:");

        lblDireccion4.setText("Hora de salida real: ");

        jLabel1.setText("Temperatura:");

        jLabel2.setText("Aeropuerto de origen:");

        jLabel3.setText("Aeropuerto de destino:");

        JMenuPrincipal.setText("Menu principal");
        JMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuPrincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMenuPrincipal);

        jPanelSalida.setText("Salidas");
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPanelSalida);

        jPanelLlegadas.setText("Llegadas");
        jPanelLlegadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLlegadasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPanelLlegadas);

        jPanelRecaudaciones.setText("Recaudaciones");
        jPanelRecaudaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRecaudacionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPanelRecaudaciones);

        jPanelVuelosCompañia.setText("Vuelos por Compañia");
        jPanelVuelosCompañia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVuelosCompañiaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPanelVuelosCompañia);

        jMenu1.setText("Ayuda");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setText("Ayuda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatos)
                                .addGap(29, 29, 29)
                                .addComponent(lblPrefijoDatos)
                                .addGap(18, 18, 18)
                                .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelfPasa2)
                                    .addComponent(lblMunicipio2)
                                    .addComponent(lblDireccion2)
                                    .addComponent(lblNombre2)
                                    .addComponent(lblModiCodigo2)
                                    .addComponent(lblTelfAero2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtModiHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModificarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                            .addComponent(txtNumPlazasOcu)
                                            .addComponent(txtModiHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addComponent(lblBorrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModificar)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrefijoBaja2)
                                .addGap(18, 18, 18)
                                .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrefijoBaja4)
                                .addGap(71, 71, 71)
                                .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelfPasa4)
                                    .addComponent(lblMunicipio4)
                                    .addComponent(lblDireccion4)
                                    .addComponent(lblNombre4)
                                    .addComponent(lblModiCodigo4)
                                    .addComponent(lblTelfAero4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDatosPrecio)
                                        .addComponent(txtDatosPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDatosLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txtDatosCod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDatosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDatosSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                    .addGap(43, 43, 43)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtTempOrigen)
                                                        .addComponent(txtTempDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))))))))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblBorrar)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrefijoBaja4)
                    .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar)
                    .addComponent(lblPrefijoBaja2)
                    .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModiCodigo2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(txtModificarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion2)
                    .addComponent(txtModiHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModiHoraLlegada)
                    .addComponent(lblMunicipio2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPlazasOcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelfPasa2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelfAero2)
                    .addComponent(bntModificar))
                .addGap(34, 34, 34)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatos)
                    .addComponent(lblPrefijoDatos)
                    .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatosCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModiCodigo4)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre4)
                    .addComponent(txtDatosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTempOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion4)
                    .addComponent(txtDatosSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTempDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatosLlegada)
                    .addComponent(lblMunicipio4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatosPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelfPasa4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatosPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelfAero4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDatos)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEliminarActionPerformed
        codigoVuelo = (String) CBEliminar.getSelectedItem();
        

    }//GEN-LAST:event_CBEliminarActionPerformed

    private void bntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarActionPerformed
        String rutaArchivo = "./src/main/resources/VuelosDiarios.csv";
        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(0).equals(codigoVuelo)) {
                    if (!txtModificarCod.getText().equals("")) {
                        lista.set(0, txtModificarCod.getText());
                        txtModificarCod.setText("");
                    } else {
                        lista.set(0, lista.get(0));
                    }
                    if (!txtModificarFecha.getText().equals("")) {
                        lista.set(1,(String) txtModificarFecha.getText());
                        txtModificarFecha.setText("");
                    } else {
                        lista.set(1, lista.get(1));
                    }
                    if (!txtModiHoraSalida.getText().equals("")) {
                        lista.set(2,(String) txtModiHoraSalida.getText());
                        txtModiHoraSalida.setText("");

                    } else {
                        lista.set(2, lista.get(2));
                    }
                    if (!txtModiHoraLlegada.getText().equals("")) {
                        lista.set(3, txtModiHoraLlegada.getText());
                        txtModiHoraLlegada.setText("");
                    } else {
                        lista.set(3, lista.get(3));
                    }
                    if (!txtNumPlazasOcu.getText().equals("")) {
                        lista.set(4, txtNumPlazasOcu.getText());
                        txtNumPlazasOcu.setText("");
                    } else {
                        lista.set(4, lista.get(4));
                    }
                    if (!txtPrecio.getText().equals("")) {
                        lista.set(5, txtPrecio.getText());
                        txtPrecio.setText("");
                    } else {
                        lista.set(5, lista.get(5));
                    }

                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

        CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaVuelosDiarios(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaVuelosDiarios(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaVuelosDiarios(CBDatos);
    }//GEN-LAST:event_bntModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String rutaArchivo = "./src/main/resources/VuelosDiarios.csv";

        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(0).equals(codigoVuelo)) {
                    continue;
                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

        CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaVuelosDiarios(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaVuelosDiarios(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaVuelosDiarios(CBDatos);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void CBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBModificarActionPerformed
       
        codigoVuelo = (String) CBModificar.getSelectedItem();
    }//GEN-LAST:event_CBModificarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        String csvFile = "./src/main/resources/VuelosDiarios.csv";
        int columnIndex = 0;
        int total = 0;

        try (CSVReader reader = new CSVReader(new FileReader(csvFile))) {
            List<String[]> data = reader.readAll();
            for (String[] row : data) {

                if (row.length > columnIndex && row[columnIndex].equals(codigoVuelo)) {
                    for (String cell : row) {
                        total++;

                        switch (total) {
                            case 1 :
                            txtDatosCod.setText(cell);
                            break;

                            case 2 :
                            txtDatosFecha.setText(cell);
                            break;

                            case 3 :
                            txtDatosSalida.setText(cell);
                            break;

                            case 4 :
                            txtDatosLlegada.setText(cell);
                            break;

                            case 5:
                            txtDatosPlazas.setText(cell);
                            break;

                            case 6 :
                            txtDatosPrecio.setText(cell);
                            break;                           

                        }
                    }
                    break;
                }
                total = 0;
            }
            
            temperatura();
        } catch (IOException | CsvException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void CBDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDatosActionPerformed
        codigoVuelo = (String) CBDatos.getSelectedItem();
    }//GEN-LAST:event_CBDatosActionPerformed

    private void JMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuPrincipalMouseClicked
         MenuInicio menu = new MenuInicio();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JMenuPrincipalMouseClicked

    private void jPanelSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseClicked
        PanelSalidas menu = new PanelSalidas();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelSalidaMouseClicked

    private void jPanelLlegadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLlegadasMouseClicked
        Llegadas menu = new Llegadas();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelLlegadasMouseClicked

    private void jPanelRecaudacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRecaudacionesMouseClicked
        PanelRecaudaciones menu = new PanelRecaudaciones();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelRecaudacionesMouseClicked

    private void jPanelVuelosCompañiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVuelosCompañiaMouseClicked
        PanelVuelosCompania menu = new PanelVuelosCompania();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelVuelosCompañiaMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AyudaVuelos ayuda = new AyudaVuelos();
        ayuda.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void temperatura(){
        String apiKey = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZmNhbGxlamEyMDE4QGdtYWlsLmNvbSIsImp0aSI6IjM2ODY1N2Q0LTY0MzYtNDUxMC04ZDNhLTM1MjQwNDRlYjJjNSIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNzAyMDUwODcwLCJ1c2VySWQiOiIzNjg2NTdkNC02NDM2LTQ1MTAtOGQzYS0zNTI0MDQ0ZWIyYzUiLCJyb2xlIjoiIn0.5GTebsglyBGax6iWlg_cbyrBN0Lc0BOlx9lOodwjiAs"; 
        String airportCode = CBDatos.getSelectedItem().toString(); 

        String apiUrl = "https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/" + airportCode + "/?api_key=" + apiKey;

        try {
            URL url = new URL(apiUrl);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                response.append(line);
            }
            reader.close();

           

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVuelosDiarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDatos;
    private javax.swing.JComboBox<String> CBEliminar;
    private javax.swing.JComboBox<String> CBModificar;
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JButton bntModificar;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jPanelLlegadas;
    private javax.swing.JMenu jPanelRecaudaciones;
    private javax.swing.JMenu jPanelSalida;
    private javax.swing.JMenu jPanelVuelosCompañia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDireccion2;
    private javax.swing.JLabel lblDireccion4;
    private javax.swing.JLabel lblModiCodigo2;
    private javax.swing.JLabel lblModiCodigo4;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblMunicipio2;
    private javax.swing.JLabel lblMunicipio4;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblPrefijoBaja2;
    private javax.swing.JLabel lblPrefijoBaja4;
    private javax.swing.JLabel lblPrefijoDatos;
    private javax.swing.JLabel lblTelfAero2;
    private javax.swing.JLabel lblTelfAero4;
    private javax.swing.JLabel lblTelfPasa2;
    private javax.swing.JLabel lblTelfPasa4;
    private javax.swing.JTextField txtDatosCod;
    private javax.swing.JTextField txtDatosFecha;
    private javax.swing.JTextField txtDatosLlegada;
    private javax.swing.JTextField txtDatosPlazas;
    private javax.swing.JTextField txtDatosPrecio;
    private javax.swing.JTextField txtDatosSalida;
    private javax.swing.JTextField txtModiHoraLlegada;
    private javax.swing.JTextField txtModiHoraSalida;
    private javax.swing.JTextField txtModificarCod;
    private javax.swing.JTextField txtModificarFecha;
    private javax.swing.JTextField txtNumPlazasOcu;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTempDestino;
    private javax.swing.JTextField txtTempOrigen;
    // End of variables declaration//GEN-END:variables
}
