/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaNegocio;

/**
 *
 * @author mfcal
 */
public class MenuVuelos extends javax.swing.JFrame {

    private static String codigoVuelo;

    /**
     * Creates new form MenuVuelos
     */
    public MenuVuelos() {
        initComponents();
        CBModificar = LogicaNegocio.rellenarListaVuelosBase(CBModificar);
        CBEliminar = LogicaNegocio.rellenarListaVuelosBase(CBEliminar);
        CBDatos = LogicaNegocio.rellenarListaVuelosBase(CBDatos);
        CBModificarAeroOrigen= LogicaNegocio.rellenarListaAeropuertos(CBModificarAeroOrigen);
        CBModificarAeroDestino =LogicaNegocio.rellenarListaAeropuertos(CBModificarAeroDestino);
        lblErrorMoidficar.setVisible(false);
        lblErrorEliminar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtModiNumPlazas = new javax.swing.JTextField();
        lblDireccion2 = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        txtModiHoraSalida = new javax.swing.JTextField();
        lblDatos = new javax.swing.JLabel();
        lblMunicipio2 = new javax.swing.JLabel();
        txtModiHoraLlegada = new javax.swing.JTextField();
        lblTelfPasa2 = new javax.swing.JLabel();
        txtModiDiasOpera = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        CBModificar = new javax.swing.JComboBox<>();
        CBDatos = new javax.swing.JComboBox<>();
        lblPrefijoDatos = new javax.swing.JLabel();
        lblPrefijoBaja4 = new javax.swing.JLabel();
        CBEliminar = new javax.swing.JComboBox<>();
        lblModiCodigo = new javax.swing.JLabel();
        txtModificarCod = new javax.swing.JTextField();
        lblTelfAero2 = new javax.swing.JLabel();
        bntModificar = new javax.swing.JButton();
        lblModiCodigo2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblPrefijoBaja2 = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        lblNombre2 = new javax.swing.JLabel();
        lblBorrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblErrorMoidficar = new javax.swing.JLabel();
        txtDatosHoraLlegada = new javax.swing.JTextField();
        lblModiCodigo1 = new javax.swing.JLabel();
        lblTelfPasa3 = new javax.swing.JLabel();
        txtDatosCodigo = new javax.swing.JTextField();
        lblTelfAero3 = new javax.swing.JLabel();
        txtDatosDiasOpera = new javax.swing.JTextField();
        lblModiCodigo3 = new javax.swing.JLabel();
        txtNumPlazas = new javax.swing.JTextField();
        lblDireccion3 = new javax.swing.JLabel();
        txtDatosHoraSalida = new javax.swing.JTextField();
        lblMunicipio3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        CBModificarAeroOrigen = new javax.swing.JComboBox<>();
        CBModificarAeroDestino = new javax.swing.JComboBox<>();
        txtDatosAeroDestino = new javax.swing.JTextField();
        txtDatosAeroOrigen = new javax.swing.JTextField();
        lblErrorEliminar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        jPanelVuelosPrevistos = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDireccion2.setText("Aeropuerto destino:");

        lblModificar.setText("MODIFICAR");

        lblDatos.setText("VER DATOS");

        lblMunicipio2.setText("Numero de plazas:");

        lblTelfPasa2.setText("Hora oficial de salida:");

        CBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBModificarActionPerformed(evt);
            }
        });

        CBDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDatosActionPerformed(evt);
            }
        });

        lblPrefijoDatos.setText("Elegir el codigo de los datos base del vuelo para ver sus datos:");

        lblPrefijoBaja4.setText("Elegir el codigo de los datos base del vuelo a eliminar:");

        CBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEliminarActionPerformed(evt);
            }
        });

        lblModiCodigo.setText("Días que opera:");

        lblTelfAero2.setText("Hora oficial de llegada:");

        bntModificar.setText("Modificar");
        bntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificarActionPerformed(evt);
            }
        });

        lblModiCodigo2.setText("Codigo:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblPrefijoBaja2.setText("Elegir el codigo de los datos base del vuelo  a modificar:");

        btnDatos.setText("Ver Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        lblNombre2.setText("Aeropuerto origen:");

        lblBorrar.setText("DAR DE BAJA");

        lblErrorMoidficar.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorMoidficar.setText("No se puede modificar");

        lblModiCodigo1.setText("Días que opera:");

        lblTelfPasa3.setText("Hora oficial de salida:");

        lblTelfAero3.setText("Hora oficial de llegada:");

        lblModiCodigo3.setText("Codigo:");

        lblDireccion3.setText("Aeropuerto destino:");

        lblMunicipio3.setText("Numero de plazas:");

        lblNombre3.setText("Aeropuerto origen:");

        CBModificarAeroOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBModificarAeroOrigenActionPerformed(evt);
            }
        });

        CBModificarAeroDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBModificarAeroDestinoActionPerformed(evt);
            }
        });

        lblErrorEliminar.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorEliminar.setText("No se puede eliminar");

        JMenuPrincipal.setText("Menu principal");
        JMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuPrincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMenuPrincipal);

        jPanelVuelosPrevistos.setText("Vuelos previstos");
        jPanelVuelosPrevistos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVuelosPrevistosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPanelVuelosPrevistos);

        jMenu1.setText("Ayuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelfPasa2)
                                    .addComponent(lblMunicipio2)
                                    .addComponent(lblDireccion2)
                                    .addComponent(lblNombre2)
                                    .addComponent(lblModiCodigo2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTelfAero2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblModiCodigo)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CBModificarAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBModificarAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtModiHoraLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                            .addComponent(txtModiDiasOpera)
                                            .addComponent(txtModiHoraSalida)
                                            .addComponent(txtModiNumPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bntModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrorMoidficar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrefijoBaja4)
                                .addGap(71, 71, 71)
                                .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatos)
                                .addGap(29, 29, 29)
                                .addComponent(lblPrefijoDatos)
                                .addGap(18, 18, 18)
                                .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBorrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModificar)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrefijoBaja2)
                                .addGap(18, 18, 18)
                                .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelfPasa3)
                                    .addComponent(lblMunicipio3)
                                    .addComponent(lblDireccion3)
                                    .addComponent(lblNombre3)
                                    .addComponent(lblModiCodigo3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTelfAero3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblModiCodigo1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatosAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatosAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDatosHoraLlegada)
                                                .addComponent(txtDatosDiasOpera)
                                                .addComponent(txtDatosHoraSalida)
                                                .addComponent(txtNumPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(txtDatosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorEliminar)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrefijoBaja4)
                    .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar)
                    .addComponent(lblPrefijoBaja2)
                    .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModiCodigo2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(CBModificarAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion2)
                    .addComponent(CBModificarAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModiNumPlazas)
                            .addComponent(lblMunicipio2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModiHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelfPasa2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModiHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelfAero2))
                        .addGap(21, 21, 21)
                        .addComponent(lblModiCodigo)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblErrorMoidficar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModiDiasOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntModificar))))
                .addGap(34, 34, 34)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatos)
                    .addComponent(lblPrefijoDatos)
                    .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModiCodigo3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre3)
                    .addComponent(txtDatosAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion3)
                    .addComponent(txtDatosAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumPlazas)
                            .addComponent(lblMunicipio3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatosHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelfPasa3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatosHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelfAero3))
                        .addGap(21, 21, 21)
                        .addComponent(lblModiCodigo1)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatosDiasOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDatos))))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBModificarActionPerformed
        String rutaArchivo = "./src/main/resources/VuelosDiarios.csv";
        boolean control=false;
        codigoVuelo = (String) CBModificar.getSelectedItem();
       try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                for (String dato : fila) {
                    if(dato.equals(codigoVuelo)){
                        control=true;
                    }
                }
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       if(control){
           lblErrorMoidficar.setVisible(true);
           bntModificar.setEnabled(false);
       }else{
           lblErrorMoidficar.setVisible(false);
           bntModificar.setEnabled(true);
       }
    }//GEN-LAST:event_CBModificarActionPerformed

    private void CBDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDatosActionPerformed
        codigoVuelo = (String) CBDatos.getSelectedItem();
    }//GEN-LAST:event_CBDatosActionPerformed

    private void CBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEliminarActionPerformed
        codigoVuelo = (String) CBEliminar.getSelectedItem();
        String rutaArchivo = "./src/main/resources/VuelosDiarios.csv";
        boolean control=false;
       try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                for (String dato : fila) {
                    if(dato.equals(codigoVuelo)){
                        control=true;
                    }
                }
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       if(control){
           lblErrorEliminar.setVisible(true);
           btnEliminar.setEnabled(false);
       }else{
           lblErrorEliminar.setVisible(false);
           btnEliminar.setEnabled(true);
       }
         
    }//GEN-LAST:event_CBEliminarActionPerformed

    private void bntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarActionPerformed
        String rutaArchivo = "./src/main/resources/VuelosBase.csv";
        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(0).equals(codigoVuelo)) {
                    if (!txtModificarCod.getText().equals("")) {
                        lista.set(0, txtModificarCod.getText());
                        txtModificarCod.setText("");
                    } else {
                        lista.set(0, lista.get(0));
                    }
                    if (!CBModificarAeroOrigen.getSelectedItem().equals("")) {
                        lista.set(1,(String) CBModificarAeroOrigen.getSelectedItem());
                    } else {
                        lista.set(1, lista.get(1));
                    }
                    if (!CBModificarAeroDestino.getSelectedItem().equals("")) {
                        lista.set(2,(String) CBModificarAeroDestino.getSelectedItem());

                    } else {
                        lista.set(2, lista.get(2));
                    }
                    if (!txtModiNumPlazas.getText().equals("")) {
                        lista.set(3, txtModiNumPlazas.getText());
                        txtModiNumPlazas.setText("");
                    } else {
                        lista.set(3, lista.get(3));
                    }
                    if (!txtModiHoraSalida.getText().equals("")) {
                        lista.set(4, txtModiHoraSalida.getText());
                        txtModiHoraSalida.setText("");
                    } else {
                        lista.set(4, lista.get(4));
                    }
                    if (!txtModiHoraLlegada.getText().equals("")) {
                        lista.set(5, txtModiHoraLlegada.getText());
                        txtModiHoraLlegada.setText("");
                    } else {
                        lista.set(5, lista.get(5));
                    }
                    if (!txtModiDiasOpera.getText().equals("")) {
                        lista.set(6, txtModiDiasOpera.getText());
                        txtModiDiasOpera.setText("");
                    } else {
                        lista.set(6, lista.get(6));
                    }
                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

        CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaVuelosBase(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaVuelosBase(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaVuelosBase(CBDatos);
    }//GEN-LAST:event_bntModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String rutaArchivo = "./src/main/resources/VuelosBase.csv";

        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(0).equals(codigoVuelo)) {
                    continue;
                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

        CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaVuelosBase(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaVuelosBase(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaVuelosBase(CBDatos);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        String csvFile = "./src/main/resources/VuelosBase.csv";
        int columnIndex = 0;
        int total = 0;

        try (CSVReader reader = new CSVReader(new FileReader(csvFile))) {
            List<String[]> data = reader.readAll();
            System.out.println("1");
            for (String[] row : data) {
                System.out.println("2");
                        
                if (row.length > columnIndex && row[columnIndex].equals(codigoVuelo)) {
                    System.out.println("3");
                    for (String cell : row) {
                        total++;
                        System.out.println("4");

                        switch (total) {
                            case 1 :
                                txtDatosCodigo.setText(cell);
                                System.out.println("Valor 1: " + cell);
                                break;
                            
                            case 2 :
                                txtDatosAeroOrigen.setText(cell);
                                System.out.println("Valor 2: " + cell);
                                break;
                            
                            case 3 :
                                txtDatosAeroDestino.setText(cell);
                                System.out.println("Valor 3: " + cell);
                                break;
                            
                            case 4 :
                                txtNumPlazas.setText(cell);
                                System.out.println("Valor 4: " + cell);
                                break;
                            
                            case 5:
                                txtDatosHoraSalida.setText(cell);
                                System.out.println("Valor 5: " + cell);
                                break;
                            
                            case 6 :
                                txtDatosHoraLlegada.setText(cell);
                                System.out.println("Valor 6: " + cell);
                                break;
                            
                            case 7:
                                txtDatosDiasOpera.setText(cell);
                                System.out.println("Valor 7: " + cell);
                                break;
                            
                        }
                    }
                    break;
                }
                total = 0;
            }
        } catch (IOException | CsvException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void CBModificarAeroOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBModificarAeroOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBModificarAeroOrigenActionPerformed

    private void CBModificarAeroDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBModificarAeroDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBModificarAeroDestinoActionPerformed

    private void JMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuPrincipalMouseClicked
        MenuInicio menu = new MenuInicio();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JMenuPrincipalMouseClicked

    private void jPanelVuelosPrevistosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVuelosPrevistosMouseClicked
        PanelVuelosPrevistos menu = new PanelVuelosPrevistos();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelVuelosPrevistosMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AyudaVuelos ayuda = new AyudaVuelos();
        ayuda.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDatos;
    private javax.swing.JComboBox<String> CBEliminar;
    private javax.swing.JComboBox<String> CBModificar;
    private javax.swing.JComboBox<String> CBModificarAeroDestino;
    private javax.swing.JComboBox<String> CBModificarAeroOrigen;
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JButton bntModificar;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jPanelVuelosPrevistos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDireccion2;
    private javax.swing.JLabel lblDireccion3;
    private javax.swing.JLabel lblErrorEliminar;
    private javax.swing.JLabel lblErrorMoidficar;
    private javax.swing.JLabel lblModiCodigo;
    private javax.swing.JLabel lblModiCodigo1;
    private javax.swing.JLabel lblModiCodigo2;
    private javax.swing.JLabel lblModiCodigo3;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblMunicipio2;
    private javax.swing.JLabel lblMunicipio3;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblPrefijoBaja2;
    private javax.swing.JLabel lblPrefijoBaja4;
    private javax.swing.JLabel lblPrefijoDatos;
    private javax.swing.JLabel lblTelfAero2;
    private javax.swing.JLabel lblTelfAero3;
    private javax.swing.JLabel lblTelfPasa2;
    private javax.swing.JLabel lblTelfPasa3;
    private javax.swing.JTextField txtDatosAeroDestino;
    private javax.swing.JTextField txtDatosAeroOrigen;
    private javax.swing.JTextField txtDatosCodigo;
    private javax.swing.JTextField txtDatosDiasOpera;
    private javax.swing.JTextField txtDatosHoraLlegada;
    private javax.swing.JTextField txtDatosHoraSalida;
    private javax.swing.JTextField txtModiDiasOpera;
    private javax.swing.JTextField txtModiHoraLlegada;
    private javax.swing.JTextField txtModiHoraSalida;
    private javax.swing.JTextField txtModiNumPlazas;
    private javax.swing.JTextField txtModificarCod;
    private javax.swing.JTextField txtNumPlazas;
    // End of variables declaration//GEN-END:variables
}
