/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaNegocio;

/**
 *
 * @author miguelfc
 */
public class MenuCompanya extends javax.swing.JFrame {

    private static String nombreCompanya;

    /**
     * Creates new form MenuCompanya
     */
    public MenuCompanya() {
        initComponents();
       CBDatos= LogicaNegocio.rellenarListaCompanya(CBDatos);
        CBEliminar=LogicaNegocio.rellenarListaCompanya(CBEliminar);
        CBModificar=LogicaNegocio.rellenarListaCompanya(CBModificar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBorrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblModificar = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        txtDatosNombre = new javax.swing.JTextField();
        lblDatosNombre = new javax.swing.JLabel();
        txtDatosDireccion = new javax.swing.JTextField();
        lblDatosDireccion = new javax.swing.JLabel();
        txtDatosMuni = new javax.swing.JTextField();
        lblDatosMunicipio = new javax.swing.JLabel();
        txtDatosTelfPasa = new javax.swing.JTextField();
        lblDatosTelfPasa = new javax.swing.JLabel();
        txtDatosTelfAero = new javax.swing.JTextField();
        txtDatosCod = new javax.swing.JTextField();
        lblDatosTelfAero = new javax.swing.JLabel();
        lblDatosCodigo = new javax.swing.JLabel();
        txtModificarCod = new javax.swing.JTextField();
        lblTelfAero2 = new javax.swing.JLabel();
        lblModiCodigo2 = new javax.swing.JLabel();
        lblPrefijoBaja2 = new javax.swing.JLabel();
        txtModiNombre = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtModiDireccion = new javax.swing.JTextField();
        lblDireccion2 = new javax.swing.JLabel();
        txtModiMuni = new javax.swing.JTextField();
        lblMunicipio2 = new javax.swing.JLabel();
        txtModiTelfPasa = new javax.swing.JTextField();
        lblTelfPasa2 = new javax.swing.JLabel();
        txtModiTelfAero = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        CBModificar = new javax.swing.JComboBox<>();
        CBDatos = new javax.swing.JComboBox<>();
        lblPrefijoDatos = new javax.swing.JLabel();
        lblPrefijoBaja4 = new javax.swing.JLabel();
        CBEliminar = new javax.swing.JComboBox<>();
        lblDatosPrefijo = new javax.swing.JLabel();
        txtCodPrefijo = new javax.swing.JTextField();
        lblModiCodigo = new javax.swing.JLabel();
        txtModiPre = new javax.swing.JTextField();
        bntModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBorrar.setText("DAR DE BAJA");

        lblModificar.setText("MODIFICAR");

        lblDatos.setText("VER DATOS");

        lblDatosNombre.setText("Nombre:");

        lblDatosDireccion.setText("Dirección:");

        lblDatosMunicipio.setText("Municipio:");

        lblDatosTelfPasa.setText("Teléfono de información al pasajero:");

        lblDatosTelfAero.setText("Teléfono de información a aeropuertos:");

        lblDatosCodigo.setText("Codigo:");

        lblTelfAero2.setText("Teléfono de información a aeropuertos:");

        lblModiCodigo2.setText("Codigo:");

        lblPrefijoBaja2.setText("Elegir la compañia a modificar:");

        lblNombre2.setText("Nombre:");

        lblDireccion2.setText("Dirección:");

        lblMunicipio2.setText("Municipio:");

        lblTelfPasa2.setText("Teléfono de información al pasajero:");

        CBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBModificarActionPerformed(evt);
            }
        });

        CBDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDatosActionPerformed(evt);
            }
        });

        lblPrefijoDatos.setText("Elegir la compañia para ver sus datos:");

        lblPrefijoBaja4.setText("Elegir la compañia a Eliminar:");

        CBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEliminarActionPerformed(evt);
            }
        });

        lblDatosPrefijo.setText("Prefijo:");

        lblModiCodigo.setText("Prefijo:");

        bntModificar.setText("Modificar");
        bntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDatos.setText("Ver Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatosMunicipio)
                                    .addComponent(lblDatosCodigo)
                                    .addComponent(lblDatosDireccion)
                                    .addComponent(lblDatosNombre))
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatosMuni, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(txtDatosCod, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDatosNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDatosDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCodPrefijo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatos)
                                .addGap(29, 29, 29)
                                .addComponent(lblPrefijoDatos)
                                .addGap(18, 18, 18)
                                .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelfAero2)
                                    .addComponent(lblTelfPasa2)
                                    .addComponent(lblMunicipio2)
                                    .addComponent(lblDireccion2)
                                    .addComponent(lblNombre2)
                                    .addComponent(lblModiCodigo2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtModiPre, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtModiTelfPasa, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                            .addComponent(txtModiTelfAero)
                                            .addComponent(txtModiMuni)
                                            .addComponent(txtModiDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtModiNombre))
                                        .addGap(107, 107, 107)
                                        .addComponent(bntModificar))))
                            .addComponent(lblBorrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrefijoBaja4)
                                .addGap(71, 71, 71)
                                .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(btnEliminar))
                            .addComponent(lblDatosPrefijo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatosTelfPasa)
                                .addGap(35, 35, 35)
                                .addComponent(txtDatosTelfPasa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModificar)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrefijoBaja2)
                                .addGap(18, 18, 18)
                                .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblModiCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatosTelfAero)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatosTelfAero, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(btnDatos)))
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1))
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuPrincipal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuPrincipal)
                .addGap(16, 16, 16)
                .addComponent(lblBorrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrefijoBaja4)
                    .addComponent(CBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificar)
                    .addComponent(lblPrefijoBaja2)
                    .addComponent(CBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModiCodigo)
                    .addComponent(txtModiPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModiCodigo2)
                    .addComponent(txtModificarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(txtModiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion2)
                            .addComponent(txtModiDireccion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMunicipio2)
                            .addComponent(txtModiMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelfPasa2)
                            .addComponent(txtModiTelfPasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblTelfAero2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModiTelfAero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntModificar)))
                .addGap(44, 44, 44)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatos)
                    .addComponent(lblPrefijoDatos)
                    .addComponent(CBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosPrefijo)
                    .addComponent(txtCodPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosCodigo)
                    .addComponent(txtDatosCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosNombre)
                    .addComponent(txtDatosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosDireccion)
                    .addComponent(txtDatosDireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosMunicipio)
                    .addComponent(txtDatosMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosTelfPasa)
                    .addComponent(txtDatosTelfPasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosTelfAero)
                    .addComponent(txtDatosTelfAero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatos))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBModificarActionPerformed

        nombreCompanya = (String) CBModificar.getSelectedItem();

    }//GEN-LAST:event_CBModificarActionPerformed

    private void CBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEliminarActionPerformed
        nombreCompanya = (String) CBEliminar.getSelectedItem();

    }//GEN-LAST:event_CBEliminarActionPerformed

    private void CBDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDatosActionPerformed
        nombreCompanya = (String) CBDatos.getSelectedItem();

    }//GEN-LAST:event_CBDatosActionPerformed

    private void bntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarActionPerformed
        String rutaArchivo = "./src/main/resources/Companyas.csv";
        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(2).equals(nombreCompanya)) {
                    if (!txtModiPre.getText().equals("")) {
                        lista.set(0, txtModiPre.getText());
                        txtModiPre.setText("");
                    } else {
                        lista.set(0, lista.get(0));
                    }
                    if (!txtModificarCod.getText().equals("")) {
                        lista.set(1, txtModificarCod.getText());
                        txtModificarCod.setText("");
                    } else {
                        lista.set(1, lista.get(1));
                    }
                    if (!txtModiNombre.getText().equals("")) {
                        lista.set(2, txtModiNombre.getText());
                        txtModiNombre.setText("");
                    } else {
                        lista.set(2, lista.get(2));
                    }
                    if (!txtModiDireccion.getText().equals("")) {
                        lista.set(3, txtModiDireccion.getText());
                        txtModiDireccion.setText("");
                    } else {
                        lista.set(3, lista.get(3));
                    }
                    if (!txtModiMuni.getText().equals("")) {
                        lista.set(4, txtModiMuni.getText());
                        txtModiMuni.setText("");
                    } else {
                        lista.set(4, lista.get(4));
                    }
                    if (!txtModiTelfPasa.getText().equals("")) {
                        lista.set(5, txtModiTelfPasa.getText());
                        txtModiTelfPasa.setText("");
                    } else {
                        lista.set(5, lista.get(5));
                    }
                    if (!txtModiTelfAero.getText().equals("")) {
                        lista.set(6, txtModiTelfAero.getText());
                        txtModiTelfAero.setText("");
                    } else {
                        lista.set(6, lista.get(6));
                    }
                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

         CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaCompanya(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaCompanya(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaCompanya(CBDatos);

    }//GEN-LAST:event_bntModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String rutaArchivo = "./src/main/resources/Companyas.csv";

        ArrayList<String[]> lineasCSV = new ArrayList<>();

        try (CSVReader csvReader = new CSVReader(new FileReader(rutaArchivo))) {
            String[] fila;
            while ((fila = csvReader.readNext()) != null) {
                lineasCSV.add(Arrays.copyOf(fila, fila.length));
            }
        } catch (IOException ex) {
            System.err.println("Error al leer el archivo CSV: " + ex.getMessage());
            return;
        } catch (CsvValidationException ex) {
            Logger.getLogger(MenuCompanya.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (CSVWriter csvWriter = new CSVWriter(new FileWriter(rutaArchivo))) {
            for (String[] fila : lineasCSV) {
                ArrayList<String> lista = new ArrayList<>(Arrays.asList(fila));

                if (lista.size() >= 3 && lista.get(2).equals(nombreCompanya)) {
                    continue;
                }

                csvWriter.writeNext(lista.toArray(new String[0]));
            }
        } catch (IOException ex) {
            System.err.println("Error al escribir en el archivo CSV: " + ex.getMessage());
        }

         CBModificar.removeAllItems();
        CBModificar = LogicaNegocio.rellenarListaCompanya(CBModificar);
        CBEliminar.removeAllItems();
        CBEliminar = LogicaNegocio.rellenarListaCompanya(CBEliminar);
        CBDatos.removeAllItems();
        CBDatos = LogicaNegocio.rellenarListaCompanya(CBDatos);

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
                String csvFile = "./src/main/resources/Companyas.csv"; 
        int columnIndex = 2; 
        int total=0;

       try (CSVReader reader = new CSVReader(new FileReader(csvFile))) {
            List<String[]> data = reader.readAll();
            for (String[] row : data) {
                if (row.length > columnIndex && row[columnIndex].equals(nombreCompanya)) {
                    for (String cell : row) {
                        total++;
                        switch (total) {
                            case 1:
                                txtCodPrefijo.setText(cell);
                                System.out.println("Valor 1: " + cell);
                                break;
                            case 2:
                                txtDatosCod.setText(cell);
                                System.out.println("Valor 2: " + cell);
                                break;
                            case 3:
                                txtDatosNombre.setText(cell);
                                System.out.println("Valor 3: " + cell);
                                break;
                            case 4:
                                txtDatosDireccion.setText(cell);
                                System.out.println("Valor 4: " + cell);
                                break;
                            case 5:
                                txtDatosMuni.setText(cell);
                                System.out.println("Valor 5: " + cell);
                                break;
                            case 6:
                                txtDatosTelfPasa.setText(cell);
                                System.out.println("Valor 6: " + cell);
                                break;
                            case 7:
                                txtDatosTelfAero.setText(cell);
                                System.out.println("Valor 7: " + cell);
                                break;
                            // Agregar más casos si hay más campos de texto
                        }
                    }
                    // Si ya se han asignado los valores, se puede salir del bucle
                    break;
                }
                total = 0;
            }
        } catch (IOException | CsvException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        MenuInicio menu = new MenuInicio();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCompanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCompanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCompanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCompanya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCompanya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDatos;
    private javax.swing.JComboBox<String> CBEliminar;
    private javax.swing.JComboBox<String> CBModificar;
    private javax.swing.JButton bntModificar;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDatosCodigo;
    private javax.swing.JLabel lblDatosDireccion;
    private javax.swing.JLabel lblDatosMunicipio;
    private javax.swing.JLabel lblDatosNombre;
    private javax.swing.JLabel lblDatosPrefijo;
    private javax.swing.JLabel lblDatosTelfAero;
    private javax.swing.JLabel lblDatosTelfPasa;
    private javax.swing.JLabel lblDireccion2;
    private javax.swing.JLabel lblModiCodigo;
    private javax.swing.JLabel lblModiCodigo2;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblMunicipio2;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPrefijoBaja2;
    private javax.swing.JLabel lblPrefijoBaja4;
    private javax.swing.JLabel lblPrefijoDatos;
    private javax.swing.JLabel lblTelfAero2;
    private javax.swing.JLabel lblTelfPasa2;
    private javax.swing.JTextField txtCodPrefijo;
    private javax.swing.JTextField txtDatosCod;
    private javax.swing.JTextField txtDatosDireccion;
    private javax.swing.JTextField txtDatosMuni;
    private javax.swing.JTextField txtDatosNombre;
    private javax.swing.JTextField txtDatosTelfAero;
    private javax.swing.JTextField txtDatosTelfPasa;
    private javax.swing.JTextField txtModiDireccion;
    private javax.swing.JTextField txtModiMuni;
    private javax.swing.JTextField txtModiNombre;
    private javax.swing.JTextField txtModiPre;
    private javax.swing.JTextField txtModiTelfAero;
    private javax.swing.JTextField txtModiTelfPasa;
    private javax.swing.JTextField txtModificarCod;
    // End of variables declaration//GEN-END:variables
}
